/*!CK:2078853147!*//*1415593752,*/

if (self.CavalryLogger) { CavalryLogger.start_js(["46btQ"]); }

__d("DocumentMentionsRegex",[],function(a,b,c,d,e,f){var g='\\.,\\+\\*\\?\\$\\@\\|#{}\\(\\)\\^\\-\\[\\]\\\\\/!%\'"~=<>_:;',h='\\b[A-Z][^\\s'+g+']',i={PUNCTUATION:g,NAME:h};e.exports=i;},null);
__d("AtSignMentionsStrategy",["DocumentMentionsRegex"],function(a,b,c,d,e,f,g){var h=g.PUNCTUATION,i=['@','\\uff20'].join(''),j='[^'+i+h+'\\s]',k='(?:'+'\\.[ |$]|'+' |'+'['+h+']|'+')',l=new RegExp('(?:^|\\s)('+'['+i+']'+'((?:'+j+k+'){0,20})'+')$'),m={findMentionableString:function(n){var o=l.exec(n);if(o!==null){var p=o[2];if(p.length)return {matchingString:p,leadOffset:o[1].length};}return null;}};e.exports=m;},null);
__d("CapitalizedNameMentionsStrategy",["DocumentMentionsRegex"],function(a,b,c,d,e,f,g){var h=1,i=new RegExp('(?:'+g.NAME+'{'+h+',})$'),j={findMentionableString:function(k){var l=i.exec(k);if(l!==null)return {matchingString:l[0],leadOffset:l[0].length};return null;}};e.exports=j;},null);
__d("DocumentCompositeMentionsSource",["emptyFunction","invariant"],function(a,b,c,d,e,f,g,h){"use strict";function i(k,l,m){var n;if(Array.isArray(l)){n=m;while(l[n-1]===null)n--;}else{var o=l.toSeq().slice(0,m).reverse().takeWhile(function(p){return p===null;}).count();n=m-o;}return k.slice(n,m);}function j(k){h(k.length>0);this.$DocumentCompositeMentionsSource0=k;this.$DocumentCompositeMentionsSource1=false;this.$DocumentCompositeMentionsSource2=null;}j.prototype.bootstrap=function(k){if(this.$DocumentCompositeMentionsSource1)return;this.$DocumentCompositeMentionsSource1=true;k=k||g;var l=this.$DocumentCompositeMentionsSource0.length;function m(){l--;if(!l)k();}this.$DocumentCompositeMentionsSource0.forEach(function(n){n.bootstrap(m);});};j.prototype.search=function(k,l,m){this.$DocumentCompositeMentionsSource3(i(k.getText(),k.getEntities(),l),m);};j.prototype.searchWithImmutables=function(k,l,m){var n=l.getAnchorKey(),o=k.getBlockForKey(n);this.$DocumentCompositeMentionsSource3(i(o.getText(),o.getEntities(),l.getAnchorOffset()),m);};j.prototype.$DocumentCompositeMentionsSource3=function(k,l){var m=this.$DocumentCompositeMentionsSource0.length,n,o;for(var p=0;p<m;p++){n=this.$DocumentCompositeMentionsSource0[p];o=n.findMatch(k);if(o===null)continue;var q=o.matchingString;this.$DocumentCompositeMentionsSource2=q;n.search(q,function(r,s){if(this.$DocumentCompositeMentionsSource2===s)l(r,o.leadOffset);}.bind(this));return;}this.$DocumentCompositeMentionsSource2=null;l(null,null);};e.exports=j;},null);
__d("DocumentMentionsSource",["invariant"],function(a,b,c,d,e,f,g){function h(i,j){"use strict";g(typeof i.findMentionableString==='function');this.$DocumentMentionsSource0=i;this.$DocumentMentionsSource1=j;this.$DocumentMentionsSource2=false;}h.prototype.findMatch=function(i){"use strict";return this.$DocumentMentionsSource0.findMentionableString(i);};h.prototype.bootstrap=function(i){"use strict";if(!this.$DocumentMentionsSource2){this.$DocumentMentionsSource2=true;this.$DocumentMentionsSource1.bootstrap(i);}};h.prototype.search=function(i,j){"use strict";this.$DocumentMentionsSource1.search(i,j);};e.exports=h;},null);
__d("FilteredSearchSource",["AbstractSearchSource"],function(a,b,c,d,e,f,g){for(var h in g)if(g.hasOwnProperty(h))j[h]=g[h];var i=g===null?null:g.prototype;j.prototype=Object.create(i);j.prototype.constructor=j;j.__superConstructor__=g;function j(k,l){"use strict";this.$FilteredSearchSource0=k;this.$FilteredSearchSource1=l;}j.prototype.bootstrapImpl=function(k){"use strict";this.$FilteredSearchSource1.bootstrap(k);};j.prototype.searchImpl=function(k,l,m){"use strict";var n=function(o,p){o=this.$FilteredSearchSource2(o,p);l(o,p);}.bind(this);this.$FilteredSearchSource1.search(k,n,m);};j.prototype.$FilteredSearchSource2=function(k,l){"use strict";var m=this.$FilteredSearchSource0;return k.filter(function(n){return m(n,l);});};e.exports=j;},null);
__d("getMentionsSearchSource",["AtSignMentionsStrategy","CapitalizedNameMentionsStrategy","DocumentCompositeMentionsSource","DocumentMentionsSource","FilteredSearchSource","SearchSourceWithMetrics","TokenizeUtil","WebAsyncSearchSource"],function(a,b,c,d,e,f,g,h,i,j,k,l,m,n){function o(t){var u={bootstrapRequests:[],queryRequests:[]};if(t._bootstrapEndpoints)t._bootstrapEndpoints.forEach(function(v){u.bootstrapRequests.push({uri:v.endpoint,data:v.data});});if(t.bootstrapEndpoint)u.bootstrapRequests.push({uri:t.bootstrapEndpoint,data:t.bootstrapData});if(t.queryEndpoint)u.queryRequests.push({uri:t.queryEndpoint,data:t.queryData});u.auxiliaryFields={authorativePerson:'is_authoritative_person',connectedPage:'connected_page',disableAutosuggest:'disable_autosuggest',renderType:'render_type',verified:'is_verified',workUser:'is_work_user'};return new n(u);}function p(t,u){var v=o(t),w=new l(v,u),x=new k(q,w);return new i([new j(g,w),new j(h,x)]);}function q(t,u){return r(t)&&(u.length>=5||s(t,u));}function r(t){var u=t.getAuxiliaryData();return !u.disableAutosuggest&&!!(t.getType()==='user'||u.connectedPage);}function s(t,u){return m.isExactMatch(u,t.getTitle());}e.exports=p;},null);